<center><b><h4>pratyush sojitra</h4></b></center>

### 1. import library

In [ ]:
import pandas as pd
import numpy as np

### 2   read csv file

In [ ]:
card = pd.read_csv("BankChurners.csv",encoding = 'ISO-8859-1')

In [ ]:
card

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [ ]:
### 3 print info
card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [ ]:
### 4 describe function
card.describe()

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
count,1.012700e+04,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,7.391776e+08,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894,0.159997,0.840003
std,3.690378e+07,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691,0.365301,0.365301
min,7.080821e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000,0.000008,0.000420
25%,7.130368e+08,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000,0.000099,0.999660
50%,7.179264e+08,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000,0.000181,0.999820
75%,7.731435e+08,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000,0.000337,0.999900
max,8.283431e+08,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000,0.999580,0.999990

In [ ]:
### 5 print column
print(card.columns)

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [ ]:
### 6 top record
card.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [ ]:
### 7 last record
card.tail(10)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
10117,712503408,Existing Customer,57,M,2,Graduate,Married,$80K - $120K,Blue,40,...,17925.0,1909,16016.0,0.712,17498,111,0.820,0.106,0.000516,0.999480
10118,713755458,Attrited Customer,50,M,1,Unknown,Unknown,$80K - $120K,Blue,36,...,9959.0,952,9007.0,0.825,10310,63,1.100,0.096,0.998130,0.001874
10119,716893683,Attrited Customer,55,F,3,Uneducated,Single,Unknown,Blue,47,...,14657.0,2517,12140.0,0.166,6009,53,0.514,0.172,0.996910,0.003088
10120,710841183,Existing Customer,54,M,1,High School,Single,$60K - $80K,Blue,34,...,13940.0,2109,11831.0,0.660,15577,114,0.754,0.151,0.000038,0.999960
10121,713899383,Existing Customer,56,F,1,Graduate,Single,Less than $40K,Blue,50,...,3688.0,606,3082.0,0.570,14596,120,0.791,0.164,0.000148,0.999850
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [ ]:
### 8 access specific coloumns
card[["Customer_Age","Gender"]]

       Customer_Age Gender
0                45      M
1                49      F
2                51      M
3                40      F
4                40      M
...             ...    ...
10122            50      M
10123            41      M
10124            44      F
10125            30      M
10126            43      F

[10127 rows x 2 columns]

In [ ]:
### 9 print types
card.dtypes

CLIENTNUM                                                                                                                               int64
Attrition_Flag                                                                                                                         object
Customer_Age                                                                                                                            int64
Gender                                                                                                                                 object
Dependent_count                                                                                                                         int64
Education_Level                                                                                                                        object
Marital_Status                                                                                                                         object
Income_Category                                                                                                                        object
Card_Category                                                                                                                          object
Months_on_book                                                                                                                          int64
Total_Relationship_Count                                                                                                                int64
Months_Inactive_12_mon                                                                                                                  int64
Contacts_Count_12_mon                                                                                                                   int64
Credit_Limit                                                                                                                          float64
Total_Revolving_Bal                                                                                                                     int64
Avg_Open_To_Buy                                                                                                                       float64
Total_Amt_Chng_Q4_Q1                                                                                                                  float64
Total_Trans_Amt                                                                                                                         int64
Total_Trans_Ct                                                                                                                          int64
Total_Ct_Chng_Q4_Q1                                                                                                                   float64
Avg_Utilization_Ratio                                                                                                                 float64
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1    float64
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2    float64
dtype: object

In [ ]:
### 10 access row by int location
card.iloc[1]

CLIENTNUM                                                                                                                                     818770008
Attrition_Flag                                                                                                                        Existing Customer
Customer_Age                                                                                                                                         49
Gender                                                                                                                                                F
Dependent_count                                                                                                                                       5
Education_Level                                                                                                                                Graduate
Marital_Status                                                                                                                                   Single
Income_Category                                                                                                                          Less than $40K
Card_Category                                                                                                                                      Blue
Months_on_book                                                                                                                                       44
Total_Relationship_Count                                                                                                                              6
Months_Inactive_12_mon                                                                                                                                1
Contacts_Count_12_mon                                                                                                                                 2
Credit_Limit                                                                                                                                     8256.0
Total_Revolving_Bal                                                                                                                                 864
Avg_Open_To_Buy                                                                                                                                  7392.0
Total_Amt_Chng_Q4_Q1                                                                                                                              1.541
Total_Trans_Amt                                                                                                                                    1291
Total_Trans_Ct                                                                                                                                       33
Total_Ct_Chng_Q4_Q1                                                                                                                               3.714
Avg_Utilization_Ratio                                                                                                                             0.105
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1             0.000057
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2              0.99994
Name: 1, dtype: object

In [ ]:
### 11 delete specific colunmn
# retail.drop("InvoiceDate",axis=1,inplace=True)

In [ ]:
#12 --specific condition
card[(card['Dependent_count']==2) & (card['Customer_Age']>30)]

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
5,713061558,Existing Customer,44,M,2,Graduate,Married,$40K - $60K,Blue,36,...,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311,0.000055,0.999940
9,719661558,Existing Customer,48,M,2,Graduate,Single,$80K - $120K,Blue,36,...,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144,0.000303,0.999700
14,712396908,Existing Customer,57,F,2,Graduate,Married,Less than $40K,Blue,48,...,2436.0,680,1756.0,1.190,1570,29,0.611,0.279,0.000114,0.999890
19,709327383,Existing Customer,45,F,2,Graduate,Married,Unknown,Blue,37,...,14470.0,1157,13313.0,0.966,1207,21,0.909,0.080,0.000055,0.999940
24,789124683,Existing Customer,54,M,2,Unknown,Married,$80K - $120K,Blue,42,...,12217.0,0,12217.0,1.075,1110,21,0.750,0.000,0.000210,0.999790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10112,708564858,Attrited Customer,33,M,2,College,Married,$120K +,Gold,20,...,34516.0,0,34516.0,1.004,9338,73,0.622,0.000,0.994380,0.005620
10117,712503408,Existing Customer,57,M,2,Graduate,Married,$80K - $120K,Blue,40,...,17925.0,1909,16016.0,0.712,17498,111,0.820,0.106,0.000516,0.999480
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [ ]:
#13 --- sum
card["Avg_Open_To_Buy"].sum()

75639977.1

In [ ]:
### 14 --------- mean
card["Avg_Open_To_Buy"].mean()

7469.139636614989

In [ ]:
###15 --- count
card["Avg_Open_To_Buy"].count()

10127

In [ ]:
###16 -- Max
card["Avg_Open_To_Buy"].max()

34516.0

In [ ]:
### 17 --min
card["Avg_Open_To_Buy"].min()

3.0

In [ ]:
### 18 -- least accurance
counts = card['Credit_Limit'].value_counts()

least_common = counts[counts == counts.min()]
least_common

Credit_Limit
2036.0     1
14566.0    1
26690.0    1
10033.0    1
11238.0    1
          ..
9183.0     1
29923.0    1
9551.0     1
11558.0    1
10388.0    1
Name: count, Length: 4428, dtype: int64

In [ ]:
### 19 --- unique entry
card["Gender"].nunique()

2

In [ ]:
### 20 --- most frequent trestbps
card["Gender"].mode()[0]

'F'

In [ ]:
### 21 ---- index
card.index

RangeIndex(start=0, stop=10127, step=1)

In [ ]:
### 22 -- no. of columns in data set
card.shape[1]

23

In [ ]:
# 23 --Nominal, Ordinal, Binary and Numeric attributes
# Nominal columns (categorical with no order)
nominal_cols = [
    'CLIENTNUM',  # ID
    'Gender',
    'Education_Level',
    'Marital_Status',
    'Income_Category',
    'Card_Category'
]

# Ordinal columns (categories with meaningful order — assumptions made)
ordinal_cols = [
    'Education_Level',  # can be ordered: High School < College < Graduate, etc.
    'Income_Category',  # e.g., <40K, 40-60K, etc. if ordered
    'Card_Category'     # e.g., Blue < Silver < Gold < Platinum
]

# Binary columns
binary_cols = [
    'Attrition_Flag'  # Typically: 1 = Attrited, 0 = Existing
]

# Numeric columns (quantitative)
numeric_cols = [
    'Customer_Age',
    'Dependent_count',
    'Months_on_book',
    'Total_Relationship_Count',
    'Months_Inactive_12_mon',
    'Contacts_Count_12_mon',
    'Credit_Limit',
    'Total_Revolving_Bal',
    'Avg_Open_To_Buy',
    'Total_Amt_Chng_Q4_Q1',
    'Total_Trans_Amt',
    'Total_Trans_Ct',
    'Total_Ct_Chng_Q4_Q1',
    'Avg_Utilization_Ratio'
]

# Naive Bayes model output (can treat as numeric or probability)
model_generated_cols = [
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
]

In [ ]:
#24-- symmetric or asymmetric
# Symmetric Binary (both values meaningful)
symmetric_binary = ['Gender']

# Asymmetric Binary (only one value is meaningful, like 1 = Attrited)
asymmetric_binary = ['Attrition_Flag']

In [ ]:
### 25 -- value count
quantity = retail['Quantity'].value_counts()
quantity

Quantity
 1        148227
 2         81829
 12        61063
 6         40868
 4         38484
           ...
-472           1
-161           1
-1206          1
-272           1
-80995         1
Name: count, Length: 722, dtype: int64

In [ ]:
# 26-- corelation
card.corr(numeric_only = True)

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
CLIENTNUM,1.000000,0.007613,0.006772,0.134588,0.006907,0.005729,0.005694,0.005708,0.000825,0.005633,0.017369,-0.019692,-0.002961,0.007696,0.000266,-0.046411,0.046410
Customer_Age,0.007613,1.000000,-0.122254,0.788912,-0.010931,0.054361,-0.018452,0.002476,0.014780,0.001151,-0.062042,-0.046446,-0.067097,-0.012143,0.007114,0.018189,-0.018189
Dependent_count,0.006772,-0.122254,1.000000,-0.103062,-0.039076,-0.010768,-0.040505,0.068065,-0.002688,0.068291,-0.035439,0.025046,0.049912,0.011087,-0.037135,0.019189,-0.019189
Months_on_book,0.134588,0.788912,-0.103062,1.000000,-0.009203,0.074164,-0.010774,0.007507,0.008623,0.006732,-0.048959,-0.038591,-0.049819,-0.014072,-0.007541,0.013693,-0.013694
Total_Relationship_Count,0.006907,-0.010931,-0.039076,-0.009203,1.000000,-0.003675,0.055203,-0.071386,0.013726,-0.072601,0.050119,-0.347229,-0.241891,0.040831,0.067663,-0.149981,0.149981
Months_Inactive_12_mon,0.005729,0.054361,-0.010768,0.074164,-0.003675,1.000000,0.029493,-0.020394,-0.042210,-0.016605,-0.032247,-0.036982,-0.042787,-0.038989,-0.007503,0.153452,-0.153452
Contacts_Count_12_mon,0.005694,-0.018452,-0.040505,-0.010774,0.055203,0.029493,1.000000,0.020817,-0.053913,0.025646,-0.024445,-0.112774,-0.152213,-0.094997,-0.055471,0.205772,-0.205772
Credit_Limit,0.005708,0.002476,0.068065,0.007507,-0.071386,-0.020394,0.020817,1.000000,0.042493,0.995981,0.012813,0.171730,0.075927,-0.002020,-0.482965,-0.023853,0.023853
Total_Revolving_Bal,0.000825,0.014780,-0.002688,0.008623,0.013726,-0.042210,-0.053913,0.042493,1.000000,-0.047167,0.058174,0.064370,0.056060,0.089861,0.624022,-0.263033,0.263032
Avg_Open_To_Buy,0.005633,0.001151,0.068291,0.006732,-0.072601,-0.016605,0.025646,0.995981,-0.047167,1.000000,0.007595,0.165923,0.070885,-0.010076,-0.538808,-0.000267,0.000267
Total_Amt_Chng_Q4_Q1,0.017369,-0.062042,-0.035439,-0.048959,0.050119,-0.032247,-0.024445,0.012813,0.058174,0.007595,1.000000,0.039678,0.005469,0.384189,0.035235,-0.131207,0.131207
Total_Trans_Amt,-0.019692,-0.046446,0.025046,-0.038591,-0.347229,-0.036982,-0.112774,0.171730,0.064370,0.165923,0.039678,1.000000,0.807192,0.085581,-0.083034,-0.168642,0.168642
Total_Trans_Ct,-0.002961,-0.067097,0.049912,-0.049819,-0.241891,-0.042787,-0.152213,0.075927,0.056060,0.070885,0.005469,0.807192,1.000000,0.112324,0.002838,-0.371403,0.371403
Total_Ct_Chng_Q4_Q1,0.007696,-0.012143,0.011087,-0.014072,0.040831,-0.038989,-0.094997,-0.002020,0.089861,-0.010076,0.384189,0.085581,0.112324,1.000000,0.074143,-0.290115,0.290115
Avg_Utilization_Ratio,0.000266,0.007114,-0.037135,-0.007541,0.067663,-0.007503,-0.055471,-0.482965,0.624022,-0.538808,0.035235,-0.083034,0.002838,0.074143,1.000000,-0.178405,0.178405
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,-0.046411,0.018189,0.019189,0.013693,-0.149981,0.153452,0.205772,-0.023853,-0.263033,-0.000267,-0.131207,-0.168642,-0.371403,-0.290115,-0.178405,1.000000,-1.000000
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2,0.046410,-0.018189,-0.019189,-0.013694,0.149981,-0.153452,-0.205772,0.023853,0.263032,0.000267,0.131207,0.168642,0.371403,0.290115,0.178405,-1.000000,1.000000

In [ ]:
# 27 ---covisiant
card.cov(numeric_only=True)

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
CLIENTNUM,1.361889e+15,2.252209e+06,324600.732489,3.966693e+07,396204.467439,213649.963677,232468.710101,1.914395e+09,2.479788e+07,1.889597e+09,140510.302192,-2.468689e+09,-2.564908e+06,67615.462278,2705.892478,-625659.593126,625659.164720
Customer_Age,2.252209e+06,6.426931e+01,-1.273041,5.051060e+01,-0.136216,0.440431,-0.163638,1.804254e+02,9.656595e+01,8.385949e+01,-0.109029,-1.264931e+03,-1.262597e+01,-0.023176,0.015724,0.053266,-0.053266
Dependent_count,3.246007e+05,-1.273041e+00,1.687163,-1.069129e+00,-0.078897,-0.014135,-0.058201,8.035358e+02,-2.845655e+00,8.063815e+02,-0.010091,1.105180e+02,1.521767e+00,0.003429,-0.013298,0.009105,-0.009105
Months_on_book,3.966693e+07,5.051060e+01,-1.069129,6.378285e+01,-0.114248,0.598592,-0.095190,5.449094e+02,5.612435e+01,4.887851e+02,-0.085712,-1.046998e+03,-9.339171e+00,-0.026757,-0.016603,0.039950,-0.039950
Total_Relationship_Count,3.962045e+05,-1.362164e-01,-0.078897,-1.142484e-01,2.416184,-0.005774,0.094923,-1.008515e+03,1.738822e+01,-1.025903e+03,0.017077,-1.833551e+03,-8.825617e+00,0.015111,0.028996,-0.085163,0.085163
Months_Inactive_12_mon,2.136500e+05,4.404313e-01,-0.014135,5.985924e-01,-0.005774,1.021358,0.032972,-1.873235e+02,-3.476571e+01,-1.525578e+02,-0.007144,-1.269686e+02,-1.014990e+00,-0.009381,-0.002090,0.056652,-0.056652
Contacts_Count_12_mon,2.324687e+05,-1.636385e-01,-0.058201,-9.519009e-02,0.094923,0.032972,1.223734,2.092991e+02,-4.860553e+01,2.579046e+02,-0.005928,-4.238033e+02,-3.952345e+00,-0.025020,-0.016917,0.083154,-0.083154
Credit_Limit,1.914395e+09,1.804254e+02,803.535812,5.449094e+02,-1008.514979,-187.323526,209.299091,8.260586e+07,3.147529e+05,8.229111e+07,25.526689,5.302297e+06,1.619802e+04,-4.370776,-1210.164705,-79.196656,79.196887
Total_Revolving_Bal,2.479788e+07,9.656595e+01,-2.845655,5.612435e+01,17.388217,-34.765710,-48.605534,3.147529e+05,6.642044e+05,-3.494515e+05,10.392768,1.782172e+05,1.072429e+03,17.436374,140.208416,-78.308907,78.308902
Avg_Open_To_Buy,1.889597e+09,8.385949e+01,806.381467,4.887851e+02,-1025.903197,-152.557816,257.904625,8.229111e+07,-3.494515e+05,8.264056e+07,15.133920,5.124080e+06,1.512559e+04,-21.807150,-1350.373120,-0.887749,0.887985
Total_Amt_Chng_Q4_Q1,1.405103e+05,-1.090290e-01,-0.010091,-8.571193e-02,0.017077,-0.007144,-0.005928,2.552669e+01,1.039277e+01,1.513392e+01,0.048052,2.954686e+01,2.813767e-02,0.020051,0.002129,-0.010507,0.010507
Total_Trans_Amt,-2.468689e+09,-1.264931e+03,110.518015,-1.046998e+03,-1833.550582,-126.968613,-423.803274,5.302297e+06,1.782172e+05,5.124080e+06,29.546861,1.154049e+07,6.436497e+04,69.218683,-77.766516,-209.280490,209.280691
Total_Trans_Ct,-2.564908e+06,-1.262597e+01,1.521767,-9.339171e+00,-8.825617,-1.014990,-3.952345,1.619802e+04,1.072429e+03,1.512559e+04,0.028138,6.436497e+04,5.509616e+02,0.627724,0.018366,-3.184618,3.184619
Total_Ct_Chng_Q4_Q1,6.761546e+04,-2.317638e-02,0.003429,-2.675664e-02,0.015111,-0.009381,-0.025020,-4.370776e+00,1.743637e+01,-2.180715e+01,0.020051,6.921868e+01,6.277243e-01,0.056685,0.004867,-0.025232,0.025232
Avg_Utilization_Ratio,2.705892e+03,1.572362e-02,-0.013298,-1.660332e-02,0.028996,-0.002090,-0.016917,-1.210165e+03,1.402084e+02,-1.350373e+03,0.002129,-7.776652e+01,1.836596e-02,0.004867,0.076006,-0.017967,0.017967
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,-6.256596e+05,5.326638e-02,0.009105,3.995004e-02,-0.085163,0.056652,0.083154,-7.919666e+01,-7.830891e+01,-8.877490e-01,-0.010507,-2.092805e+02,-3.184618e+00,-0.025232,-0.017967,0.133445,-0.133445
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2,6.256592e+05,-5.326626e-02,-0.009105,-3.995006e-02,0.085163,-0.056652,-0.083154,7.919689e+01,7.830890e+01,8.879850e-01,0.010507,2.092807e+02,3.184619e+00,0.025232,0.017967,-0.133445,0.133445